# Generated by Django 2.0.3 on 2019-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList_jingcai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='MatchList',
            new_name='MatchList_quanbu',
        ),
    ]
