# Generated by Django 2.0.3 on 2019-08-04 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190727_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 6, 3, 34, 249197), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
