# Generated by Django 2.0.3 on 2019-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191021_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchList_jingcai',
        ),
        migrations.AddField(
            model_name='matchlist_quanbu',
            name='matchNoCn',
            field=models.CharField(blank=True, help_text='官方竞彩场次', max_length=50, null=True, verbose_name='官方竞彩场次'),
        ),
    ]
