# Generated by Django 2.0.3 on 2019-08-16 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190804_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aicaiAwayId', models.IntegerField(help_text='爱彩客队ID', max_length=50, verbose_name='爱彩客队ID')),
                ('aicaiHomeId', models.IntegerField(help_text='爱彩主队ID', max_length=50, verbose_name='爱彩主队ID')),
                ('aicaiLeagueId', models.IntegerField(help_text='爱彩联赛ID', max_length=50, verbose_name='爱彩联赛ID')),
                ('awayId', models.IntegerField(help_text='客队ID', max_length=50, verbose_name='客队ID')),
                ('awayLogo', models.CharField(help_text='客队LOGO地址', max_length=500, verbose_name='客队LOGO地址')),
                ('awayName', models.CharField(help_text='客队名称', max_length=50, verbose_name='客队名称')),
                ('awayRank', models.CharField(help_text='客队排名', max_length=50, verbose_name='客队排名')),
                ('bigsmall', models.CharField(help_text='大小球盘口', max_length=50, verbose_name='大小球盘口')),
                ('card', models.CharField(help_text='红黄牌', max_length=50, verbose_name='红黄牌')),
                ('corner', models.CharField(help_text='角球', max_length=50, verbose_name='角球')),
                ('elapsedTime', models.CharField(help_text='比赛进行时间', max_length=50, verbose_name='比赛进行时间')),
                ('homeId', models.IntegerField(help_text='主队ID', max_length=50, verbose_name='主队ID')),
                ('homeLogo', models.CharField(help_text='主队LOGO地址', max_length=500, verbose_name='主队LOGO地址')),
                ('homeName', models.CharField(help_text='主队名称', max_length=50, verbose_name='主队名称')),
                ('homeRank', models.CharField(help_text='主队排名', max_length=50, verbose_name='主队排名')),
                ('isCartoon', models.BooleanField(default=False, help_text='是否有动画直播', verbose_name='是否有动画直播')),
                ('isVideo', models.BooleanField(default=False, help_text='是否有视频直播', verbose_name='是否有视频直播')),
                ('leagueColor', models.CharField(help_text='联赛颜色', max_length=50, verbose_name='联赛颜色')),
                ('leagueId', models.IntegerField(help_text='联赛ID', max_length=50, verbose_name='联赛ID')),
                ('leagueName', models.CharField(help_text='联赛名称', max_length=50, verbose_name='联赛名称')),
                ('leagueType', models.IntegerField(help_text='联赛类型', max_length=50, verbose_name='联赛类型')),
                ('matchDate', models.DateTimeField(help_text='比赛开始日期', max_length=50, verbose_name='比赛开始日期')),
                ('matchId', models.IntegerField(help_text='比赛ID', max_length=50, verbose_name='比赛ID')),
                ('matchTime', models.CharField(help_text='比赛开始时间', max_length=50, verbose_name='比赛开始时间')),
                ('middle', models.BooleanField(help_text='是否中立场地', verbose_name='是否中立场地')),
                ('oddsAsia', models.CharField(help_text='亚盘赔率', max_length=50, verbose_name='亚盘赔率')),
                ('oddsEurope', models.CharField(help_text='欧盘赔率', max_length=50, verbose_name='欧盘赔率')),
                ('qtMatchId', models.IntegerField(help_text='qt比赛ID', max_length=50, verbose_name='qt比赛ID')),
                ('score', models.CharField(help_text='比分数据', max_length=50, verbose_name='比分数据')),
                ('status', models.IntegerField(help_text='比赛进行状态', max_length=50, verbose_name='比赛进行状态')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 28, 47, 106256), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
