# Generated by Django 2.0.3 on 2019-08-16 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190816_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 29, 3, 268939), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
