# Generated by Django 2.0.3 on 2019-08-16 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190816_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 32, 11, 311921), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='matchId',
            field=models.IntegerField(help_text='比赛ID', max_length=50, primary_key=True, serialize=False, verbose_name='比赛ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='middle',
            field=models.BooleanField(default=False, help_text='是否中立场地', verbose_name='是否中立场地'),
        ),
    ]
