# Generated by Django 2.0.3 on 2019-08-16 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190816_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 35, 1, 776340), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiAwayId',
            field=models.IntegerField(help_text='爱彩客队ID', verbose_name='爱彩客队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiHomeId',
            field=models.IntegerField(help_text='爱彩主队ID', verbose_name='爱彩主队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiLeagueId',
            field=models.IntegerField(help_text='爱彩联赛ID', verbose_name='爱彩联赛ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='awayId',
            field=models.IntegerField(help_text='客队ID', verbose_name='客队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='homeId',
            field=models.IntegerField(help_text='主队ID', verbose_name='主队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='leagueId',
            field=models.IntegerField(help_text='联赛ID', verbose_name='联赛ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='qtMatchId',
            field=models.IntegerField(help_text='qt比赛ID', verbose_name='qt比赛ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='status',
            field=models.IntegerField(help_text='比赛进行状态', verbose_name='比赛进行状态'),
        ),
    ]
