# Generated by Django 2.0.3 on 2019-08-16 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190816_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 35, 44, 596923), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='leagueType',
            field=models.IntegerField(help_text='联赛类型', verbose_name='联赛类型'),
        ),
    ]
