# Generated by Django 2.0.3 on 2019-08-16 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190816_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 36, 15, 97489), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='matchId',
            field=models.IntegerField(help_text='比赛ID', primary_key=True, serialize=False, verbose_name='比赛ID'),
        ),
    ]
