# Generated by Django 2.0.3 on 2019-08-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190816_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 37, 24, 751167), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='matchDate',
            field=models.DateTimeField(blank=True, help_text='比赛开始日期', max_length=50, verbose_name='比赛开始日期'),
        ),
    ]
