# Generated by Django 2.0.3 on 2019-08-16 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190816_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 10, 40, 15, 732235), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
