# Generated by Django 2.0.3 on 2019-08-16 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190816_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 22, 44, 16, 781531), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiAwayId',
            field=models.IntegerField(blank=True, help_text='爱彩客队ID', verbose_name='爱彩客队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiHomeId',
            field=models.IntegerField(blank=True, help_text='爱彩主队ID', verbose_name='爱彩主队ID'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='aicaiLeagueId',
            field=models.IntegerField(blank=True, help_text='爱彩联赛ID', verbose_name='爱彩联赛ID'),
        ),
    ]
