# Generated by Django 2.0.3 on 2019-08-16 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20190816_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 22, 47, 50, 704807), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='corner',
            field=models.CharField(blank=True, help_text='角球', max_length=50, null=True, verbose_name='角球'),
        ),
    ]
