# Generated by Django 2.0.3 on 2019-08-17 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190816_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMatchVo',
            fields=[
                ('awayRank', models.CharField(help_text='客队排名', max_length=50, verbose_name='客队排名')),
                ('awayTeamId', models.IntegerField(help_text='客队ID', verbose_name='客队ID')),
                ('awayTeamLogo', models.CharField(help_text='客队LOGO', max_length=50, verbose_name='客队LOGO')),
                ('awayTeamName', models.CharField(help_text='客队名称', max_length=50, verbose_name='客队名称')),
                ('elapsedTime', models.CharField(help_text='比赛进行时间', max_length=50, verbose_name='比赛进行时间')),
                ('existGroupMatch', models.IntegerField(help_text='??', verbose_name='??')),
                ('homeRank', models.CharField(help_text='主队排名', max_length=50, verbose_name='主队排名')),
                ('homeTeamId', models.IntegerField(help_text='主队ID', verbose_name='主队ID')),
                ('homeTeamLogo', models.CharField(help_text='主队LOGO', max_length=50, verbose_name='主队LOGO')),
                ('homeTeamName', models.CharField(help_text='主队名称', max_length=50, verbose_name='主队名称')),
                ('leagueId', models.IntegerField(help_text='联赛ID', verbose_name='联赛ID')),
                ('leagueMatchId', models.IntegerField(help_text='比赛ID', primary_key=True, serialize=False, verbose_name='比赛ID')),
                ('leagueName', models.CharField(help_text='联赛名称', max_length=50, verbose_name='联赛名称')),
                ('leagueSeasonId', models.IntegerField(help_text='联赛季节ID', verbose_name='联赛季节ID')),
                ('leagueStageId', models.IntegerField(help_text='联赛阶段ID', verbose_name='联赛阶段ID')),
                ('leagueType', models.IntegerField(help_text='联赛类型', verbose_name='联赛类型')),
                ('matchStatus', models.IntegerField(help_text='比赛状态', verbose_name='比赛状态')),
                ('matchTime', models.CharField(help_text='比赛开始时间', max_length=50, verbose_name='比赛开始时间')),
                ('middle', models.BooleanField(help_text='是否中立场', verbose_name='是否中立场')),
                ('qtMatchId', models.IntegerField(blank=True, help_text='???', null=True, verbose_name='???')),
                ('score', models.CharField(blank=True, help_text='比分', max_length=50, null=True, verbose_name='比分')),
                ('seasonFlag', models.IntegerField(blank=True, help_text='联赛季节旗帜', null=True, verbose_name='联赛季节旗帜')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 9, 59, 56, 787687), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
