# Generated by Django 2.0.3 on 2019-08-19 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20190817_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStanding',
            fields=[
                ('attackToScoreRate', models.FloatField(help_text='赛果', max_length=200, verbose_name='进球转化率')),
                ('averageLost', models.FloatField(help_text='？？', max_length=200, verbose_name='？？')),
                ('averageScore', models.FloatField(help_text='？？', max_length=200, verbose_name='？？')),
                ('beCornerKick', models.FloatField(help_text='被罚角球', max_length=200, verbose_name='被罚角球')),
                ('beFreeKick', models.FloatField(help_text='被罚任意球', max_length=200, verbose_name='被罚任意球')),
                ('beShootOn', models.FloatField(help_text='被射正', max_length=200, verbose_name='被射正')),
                ('beShooted', models.FloatField(help_text='被射门', max_length=200, verbose_name='被射门')),
                ('control', models.FloatField(help_text='控球比例', max_length=200, verbose_name='控球比例')),
                ('cornerKick', models.FloatField(help_text='角球', max_length=200, verbose_name='角球')),
                ('dangerousAttack', models.FloatField(help_text='危险进攻次数', max_length=200, verbose_name='危险进攻次数')),
                ('freeKick', models.FloatField(help_text='任意球次数', max_length=200, verbose_name='任意球次数')),
                ('halfControlRate', models.FloatField(help_text='半场控球比例', max_length=200, verbose_name='半场控球比例')),
                ('lostScoreRate', models.FloatField(help_text='失分比例', max_length=200, verbose_name='失分比例')),
                ('shoot', models.FloatField(help_text='射门次数', max_length=200, verbose_name='射门次数')),
                ('shootOn', models.FloatField(help_text='射正次数', max_length=200, verbose_name='射正次数')),
                ('leagueMatchId', models.IntegerField(help_text='比赛ID', primary_key=True, serialize=False, verbose_name='比赛ID')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 20, 47, 37, 901460), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
