# Generated by Django 2.0.3 on 2019-08-19 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20190819_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstanding',
            name='awayId',
            field=models.IntegerField(blank=True, help_text='客队ID', null=True, verbose_name='客队ID'),
        ),
        migrations.AddField(
            model_name='matchstanding',
            name='awayLogo',
            field=models.CharField(blank=True, help_text='客队LOGO地址', max_length=250, null=True, verbose_name='客队LOGO地址'),
        ),
        migrations.AddField(
            model_name='matchstanding',
            name='awayName',
            field=models.CharField(blank=True, help_text='客队名称', max_length=50, null=True, verbose_name='客队名称'),
        ),
        migrations.AddField(
            model_name='matchstanding',
            name='homeId',
            field=models.IntegerField(blank=True, help_text='主队ID', null=True, verbose_name='主队ID'),
        ),
        migrations.AddField(
            model_name='matchstanding',
            name='homeLogo',
            field=models.CharField(blank=True, help_text='主队LOGO地址', max_length=250, null=True, verbose_name='主队LOGO地址'),
        ),
        migrations.AddField(
            model_name='matchstanding',
            name='homeName',
            field=models.CharField(blank=True, help_text='主队名称', max_length=50, null=True, verbose_name='主队名称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 21, 38, 26, 327002), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
